using System;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Text;

internal static class Program
{
    private static string RunGitDescribe()
    {
        var psi = new ProcessStartInfo
        {
            FileName = "git",
            Arguments = "describe --tags --dirty --always",
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true
        };

        using var p = Process.Start(psi);

        if (p == null)
            throw new InvalidOperationException("Failed to start 'git' process.");

        var stdout = p.StandardOutput.ReadToEnd().Trim();
        var stderr = p.StandardError.ReadToEnd().Trim();
        p.WaitForExit();

        if (p.ExitCode != 0)
            throw new InvalidOperationException(string.Format("git describe failed (exit {0}). {1}", p.ExitCode, stderr));

        if (string.IsNullOrWhiteSpace(stdout))
            throw new InvalidOperationException("git describe returned empty output.");

        return stdout;
    }

    private static string ParseVersion(string describe)
    {
        var parts = describe.Split('-');
        var version = parts[0];
        if (version.StartsWith("v"))
            version = version.Substring(1);
        var commitCount = parts.Length > 1 ? parts[1] : "0";
        var suffix = parts.Length > 2 ? "-dev" : "";
        return $"{version}.{commitCount}{suffix}";
    }

    public static int Main(string[] args)
    {
        if (args.Length != 4)
        {
            Console.WriteLine("Usage: VersionGenerator <output_path> <AssemblyName> <AssemblyGuid> <about_xml_path>");
            throw new ArgumentException("Invalid number of arguments");
        }

        var outPath = args[0];
        var ns = "ThisAssembly";

        var describe = RunGitDescribe();
        var versionLong = ParseVersion(describe);
        var parts = versionLong.Split('-');
        var vTokens = parts[0].Split('.');
        var version = parts[0];
        var versionSuffix = parts.Length > 1 ? parts[1] : "";
        var versionMajor = int.Parse(vTokens[0], CultureInfo.InvariantCulture);
        var versionMinor = int.Parse(vTokens.Length > 1 ? vTokens[1] : "0", CultureInfo.InvariantCulture);
        var versionPatch = int.Parse(vTokens.Length > 2 ? vTokens[2] : "0", CultureInfo.InvariantCulture);
        var versionCommits = int.Parse(vTokens.Length > 3 ? vTokens[3] : "0", CultureInfo.InvariantCulture);
        var buildTime = DateTime.UtcNow.ToString("O");

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine(string.Format("// Generated at {0}", buildTime));
        sb.AppendLine(string.Format("// Source: git describe --tags --dirty --always => {0}", describe));
        sb.AppendLine();
        sb.AppendLine(string.Format("namespace {0};", ns));
        sb.AppendLine();
        sb.AppendLine("internal static class ModInfo");
        sb.AppendLine("{");
        sb.AppendLine($"    public const int VersionMajor = {versionMajor};");
        sb.AppendLine($"    public const int VersionMinor = {versionMinor};");
        sb.AppendLine($"    public const int VersionPatch = {versionPatch};");
        sb.AppendLine($"    public const int VersionCommits = {versionCommits};");
        sb.AppendLine($"    public const string Version = @\"{version.Replace("\"", "\"\"")}\";");
        sb.AppendLine($"    public const string VersionLong = @\"{versionLong.Replace("\"", "\"\"")}\";");
        sb.AppendLine($"    public const string VersionGit = @\"{describe.Replace("\"", "\"\"")}\";");
        sb.AppendLine($"    public const string VersionSuffix = @\"{versionSuffix.Replace("\"", "\"\"")}\";");
        sb.AppendLine($"    public const string AssemblyName = @\"{args[1]}\";");
        sb.AppendLine($"    public const string AssemblyGuid = @\"{args[2]}\";");
        sb.AppendLine($"    public const string BuiltTime = \"{buildTime}\";");
        sb.AppendLine("}");
        sb.AppendLine();

        var fullOutPath = Path.GetFullPath(outPath);
        var dir = Path.GetDirectoryName(fullOutPath);
        if (!string.IsNullOrEmpty(dir))
            Directory.CreateDirectory(dir);

        File.WriteAllText(outPath, sb.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

        Console.WriteLine($"Wrote version {versionLong} to: {outPath}");

        var aboutPath = args[3];

        if (!string.IsNullOrWhiteSpace(aboutPath) && File.Exists(aboutPath))
        {
            var xml = File.ReadAllText(aboutPath, Encoding.UTF8);

            var doc = System.Xml.Linq.XDocument.Parse(xml, System.Xml.Linq.LoadOptions.PreserveWhitespace);
            var root = doc.Root;

            if (root != null)
            {
                var versionEl = root.Element("Version");
                if (versionEl != null)
                    versionEl.Value = versionLong;

                File.WriteAllText(aboutPath, doc.ToString(System.Xml.Linq.SaveOptions.DisableFormatting), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            }
        }
        return 0;
    }
}
