name: Build and Release Mod
description: Build and release a Stationeers mod

runs:
  using: composite
  steps:
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "9.0.x"

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: 0
        submodules: recursive
        lfs: true
        clean: false

    - name: Fetch Git LFS objects in Template
      shell: bash
      run: |
        git submodule foreach git lfs pull
        git submodule foreach git lfs checkout

    - name: Build project
      shell: bash
      run: |
        python Template/download_dependencies.py
        dotnet restore
        dotnet build --configuration Release Main.csproj

    - name: Package DLL and About folder
      if: github.ref_type == 'tag' || github.ref == 'refs/heads/main'
      id: package_zip
      shell: bash
      run: |
        set -euo pipefail

        # 1) Find the first compiled DLL
        DLL_PATH=$(find ./bin/Release -type f -name '*.dll' | head -n 1)
        echo "Found DLL at: $DLL_PATH"

        # 2) Get base name (without extension) and version from tag
        DLL_FILENAME=$(basename "$DLL_PATH")        # e.g. MyMod.dll
        BASE_NAME="${DLL_FILENAME%.dll}"            # e.g. MyMod
        VERSION="${GITHUB_REF_NAME}"                # e.g. v1.2.3 (tag name)

        # 3) Build zip name: MyMod-v1.2.3.zip
        ZIP_NAME="${BASE_NAME}-${VERSION}.zip"

        # 4) Build package structure
        mkdir -p dist/$BASE_NAME
        mkdir -p dist/release
        cp "$DLL_PATH" dist/$BASE_NAME/
        cp -r About dist/$BASE_NAME/

        # 5) Create zip (DLL + About folder)
        (cd dist/$BASE_NAME && zip -r "../release/$ZIP_NAME" .)

        # 6) Expose zip path as output for later steps (e.g. upload to release)
        echo "zip_path=dist/$ZIP_NAME" >> "$GITHUB_OUTPUT"
        echo "Created package: dist/$ZIP_NAME"

    - name: Create GitHub Release
      if: github.ref_type == 'tag' || github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: dist/release/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run modrepo builder action
      uses: aproposmath/modrepo-builder-action@v1
      if: github.ref_type == 'tag' || github.ref == 'refs/heads/main'
